### ISSUE TITLE
Issues to fix for the next version of the artifact

### ISSUE THREAD

**Issue by adl** [xblahoud/seminator-evaluation#1]
These were reported by a reviewer:

1. Running the notebook `Formulae.ipynb` create files of formulas that differs from those in the repository.  I believe this is because the formulas were generated by an older version of Spot (maybe 2.7.x) and we never recomputed them in the notebook.

2. The last, disabled cell of `complement/Run_ltlcross.ipynb` starts with `no_tools = {t:or cmd for t,cmd...`.  This should be `no_tools = {t: cmd for t,cmd...` 

Additionally:

3.  Cell `[9]` of `Formulae.ipynb` currently contains an output line `Automata of type cd:	0`, but the code cannot output this line.  This should disappear when the file is reexecuted.

4. `complement/Run_ltlcross.ipynb` contains the typo "chenge".

**Comment by xblahoud** [comment]
1. and 3. are solved by 6218a32

**Comment by xblahoud** [comment]
4. is solved by 3994142
